### PR TITLE
Julia 0.7

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by danimad** [comment]
I updated the Travis and AppVeyor build files in #190.
However there is a StackOverflowError when I build the package:
```
ERROR: LoadError: LoadError: StackOverflowError:
Stacktrace:
 [1] getproperty at ./sysimg.jl:18 [inlined]
 [2] find_and_translate_transparent_identifier(::Expr) at /home/travis/build/danimad/Query.jl/src/query_translation.jl:437
 [3] find_and_translate_transparent_identifier(::Expr) at /home/travis/build/danimad/Query.jl/src/query_translation.jl:441 (repeats 29057 times)
 [4] query_expression_translation_phase_7 at /home/travis/build/danimad/Query.jl/src/query_translation.jl:448 [inlined]
 [5] translate_query(::Expr) at /home/travis/build/danimad/Query.jl/src/query_translation.jl:504
 [6] @from(::LineNumberNode, ::Module, ::Expr, ::Expr) at /home/travis/build/danimad/Query.jl/src/Query.jl:41
 [7] include at ./boot.jl:317 [inlined]
 [8] include_relative(::Module, ::String) at ./loading.jl:1038
 [9] include(::Module, ::String) at ./sysimg.jl:29
 [10] include(::String) at ./client.jl:398
 [11] top-level scope at none:0
in expression starting at /home/travis/build/danimad/Query.jl/test/runtests.jl:247
```
There is an error with handling queries that have two @from clauses for example.
Sorry, I don't know how to fix it, I just started to learn Julia, and wanted to install the Queryverse package, and I'm trying since 2 weeks to get it building 😄

**Comment by jingpengw** [comment]
any plan to get this going? Femtocleaner.jl might help here?

**Comment by davidanthoff** [comment]
I was on vacation :) Hopefully I'll be able to finish this soon.

**Comment by davidanthoff** [comment]
So, I'm getting there...

Everything except the tests in https://github.com/queryverse/Query.jl/blob/master/test/test_pipesyntax.jl are working now. But, I can't figure out why those tests don't work anymore... I've stared at this for so long now (and tried different things) that I'm a bit lost what else to do.... If someone else (@bramtayl?) could take a fresh look, it would be really appreciated!

There are then still a number of lose ends to fix, but those are easy and I'll try to do them tomorrow.

**Comment by bramtayl** [comment]
So the bug you're running into here is that lowering now automatically inserts the line number as the first argument of every macro. So when you build the `@from` macro expression inside `@query` you're gonna wanna insert `@__LINE__` as the first argument to `@from`. Otherwise, the parser interprets the `in` call as a line number and gets confused. You might need a switch here based on version number if you want backwards compatibility. The other option would to be to forget the `Expr` calls and simply interpolate everything into a single expression (and lowering will take care of the line number automatically). The downside of this is you get less control over line numbers; the line numbers that will end up getting inserted would be the line numbers from the macro itself rather than the line numbers from user code. The second note I'd add is to make the errors inside the `@from` and `@query` macros more informative. I think that should be enough to start?

**Comment by davidanthoff** [comment]
Ok, so I've resolve the issue above, but that test still doesn't work... I think there is some error with escaping, i.e. I assume something must have changed in julia 0.7, but I can't figure it out... @bramtayl any chance you might be able to help again?

> The second note I'd add is to make the errors inside the @from and @query macros more informative. I think that should be enough to start?

Yeah, error messages right now are a total mess...

**Comment by bramtayl** [comment]
One thing I do in my macros is just avoid all escaping at all. That is, I build a bunch of nested functions for transforming expressions. To avoid hygiene issues you need to interpolate in all functions and make sure all introduced variables are gensyms.  Then at the end dedicate macros only to escaping. So `macro @from(something); esc(from(something)); end`. It's a bit unorthodox but for me its worth it so I never have to worry about escaping.

**Comment by bramtayl** [comment]
But anyways if you change the last line of `@query` to `x = :($f_arg -> $Query.@from $in($range, $f_arg) $body) |> esc` and the condition in `@from` to `range.head!=:call || (range.args[1]!=:in && range.args[1]!=in)` it should do the trick. `@from` was getting confused by being passed an escaped body.

**Comment by davidanthoff** [comment]
@bramtayl Hurray, thank you so much, that did the trick!!!

So, here is the game plan: I'll merge this into ``master`` tonight after one final review. I then need to fix a few smaller things, go through the doc once, and then will tag and release.

**Pull request merged**
