### PR TITLE
Rewrote the parser using macrotools

### PR DESCRIPTION
**Pull request by bramtayl**
I've rewritten the parser using macrotools. I've also added chaining to the code. A further step I might do eventually is use NumberedLines to retain line number information.

### CODE REVIEW

**Comment by bramtayl** [comment]
Something odd happened to the indentation... it's rendering fine in Juno so I'll have to do some investigating

**Comment by bramtayl** [comment]
Coverage statistics are broken due to a bug in MacroTools that is fixed on master

**Comment by davidanthoff** [comment]
@bramtayl Thanks.

I'm not sure what to do with this right now... For starters, I'm worried about taking a dependency on MacroTools.jl. As far as I can tell that package doesn't have a full proper CI, code coverage setup, and I wouldn't want to depend on a package without that.

The bigger issue is that right now I don't understand the new code you wrote, probably mostly because I'm not familiar with MacroTools. So before I can even consider merging this, I would have to find the time to understand this code, which I don't have right now. So I think for now I'm afraid this will just sit here for a couple of weeks (if not months) until I find time for that...

I guess my general advice here would be to inquire with a package owner before you spend a lot of time rewriting core parts of the package. Even if the rewrite is fantastic (it might well be!) it can often be the case that the owner of the package doesn't want to merge such a big rewrite for some other reason. So, I really appreciate that you want to help, but for now I just don't have the bandwidth to look at this in detail, I'm afraid.

**Comment by bramtayl** [comment]
Thats ok! I'm pretty sure it will be useful eventually.

As for the stability of MacroTools, the travis log is here
https://travis-ci.org/MikeInnes/MacroTools.jl
though you're right I don't see anything about code coverage. FWIW, my impression is that it is a fairly widely used and stable package.

```
julia> Pkg.dependents("MacroTools")
20-element Array{AbstractString,1}:
 "CodeTools"
 "LazyCall"
 "IntervalConstraintProgramming"
 "Media"
 "Lazy"
 "Blink"
 "ChainMap"
 "Weber"
 "QuickTypes"
 "ChainRecursive"
 "Atom"
 "SimpleTraits"
 "Juno"
 "ScikitLearn"
 "ClobberingReload"
 "PyCall"
 "DataFlow"
 "TreeView"
 "Jewel"
 "Hiccup"
```

**Comment by bramtayl** [comment]
P.S. here's a code comparison to see what kind of changes I made:

Original:
```julia
		elseif length(qe)>=3 && qe[1].head==:macrocall && qe[1].args[1]==Symbol("@from") && qe[2].head==:macrocall && qe[2].args[1]==Symbol("@join") && length(qe[2].args)==8 && qe[3].head==:macrocall && qe[3].args[1]==Symbol("@select")
			e1 = qe[1].args[2].args[3]
			e2 = qe[2].args[2].args[3]
			x1 = qe[1].args[2].args[2]
			x2 = qe[2].args[2].args[2]
			k1 = qe[2].args[4]
			k2 = qe[2].args[6]
			g = qe[2].args[8]
			v = qe[3].args[2]
			f_outer_key = Expr(:->, x1, k1)
			f_inner_key = Expr(:->, x2, k2)
			f_result = Expr(:->, Expr(:tuple,x1,g), v)
			qe[1] = :( Query.@group_join_internal($e1, $e2, $(esc(f_outer_key)), $(esc(f_inner_key)), $(esc(f_result))) )
-
-			deleteat!(qe,3)
-			deleteat!(qe,2)
```

After:
```
        (@join innerIterator_ in innerSource_ on outerKey_ equals innerKey_ into group_) => begin
            with_user_selection(es, outerIterator, group) do selection
                :(Query.@group_join_internal $outerSource $innerSource $(anon(outerIterator, outerKey)) $(anon(innerIterator, innerKey)) $selection)
            end
        end
```

**Comment by bramtayl** [comment]
Still think this might make things a bit nicer, but I don't really have the energy to do it if things are already working

**Comment by bramtayl** [comment]
If you're still interested in this I could have another go. Now that MacroTools is working with 1.0 I don't see a huge problem with having it as a dependency.

**Comment by davidanthoff** [comment]
I'm kicking myself everyday now that I didn't accept this PR long ago! That was a huge mistake, and now that I'm trying to get things to work on 1.0 it would have been sooo much easier. Sorry for my misjudgment there.

If you still have the energy to do this, it would be awesome! In general, if you wanted to contribute to this package, it would be fantastic! Many of the things you experimented with over the last couple of years were great and I'd love to see you bring all the experience in here!

We do have to make sure we coordinate this with the 0.7 update work that I'm in the middle of... Maybe the safest way would be that we first try to get a 0.7 compatible version out based on the old code, and then if you want to have a go at using MacroTools for this you do that after that?

**Comment by bramtayl** [comment]
Ok sounds good!

**Comment by bramtayl** [comment]
Ok, so I rewrote a bunch of code using MacroTools based the 0.7 branch. I can create a PR if you're interested. It was a ton of work, but it also got me thinking. I've been working on chaining/lazy call syntax for a long time and have a trash heap of discarded ideas (so take this with a grain of salt). But my favorite right now took a bit of inspiration for your underscore syntax for anonymous functions: a macro to make simple anonymous functions with an arbitrary number of _, __, etc. arguments. I've got it written if you're interested. Here's an example I took from the docs:

```
df_parents |>
    (@_ join(_, df_children, (@_ _.Name), (@_ _.Parent), (@_ (Parent=_.Name, Child=__.Name)) |> 
    DataFrame
```

**Comment by davidanthoff** [comment]
> Ok, so I rewrote a bunch of code using MacroTools based the 0.7 branch. I can create a PR if you're interested. It was a ton of work

Yes, that would be great! I merged the 0.7 branch into ``master``, so you can just start off that.

If there is a way to do this in smaller steps, i.e. multiple smaller PRs, it would make things easier for me to review. BUT, if that is too much work, I'd still prefer even a big PR, really anything to get rid of the horror that this code is right now :)

> I've been working on chaining/lazy call syntax for a long time and have a trash heap of discarded ideas (so take this with a grain of salt). But my favorite right now took a bit of inspiration for your underscore syntax for anonymous functions: a macro to make simple anonymous functions with an arbitrary number of _, __, etc. arguments. I've got it written if you're interested. Here's an example I took from the docs:

That is interesting! Having said that, I think Query.jl itself is really entering a phase of stability. So I was hoping to add lots of new features, but essentially int he framework that we have today, and not play around with the basic structure anymore. I'm going to remove the "experimental" designator from the standalone versions really soon, and then I think we'll have two front ends in the Query.jl package: the LINQ style and the standalone style.

I DO think it would be valuable to continue experimenting with other models, I can certainly imagine that we can find a better design than Query.jl. But I think maybe that could be done in a different package? It could still use the QueryOperators.jl backend stuff?

**Pull request closed without merging**
